services:
  nginx-of-bind-mount:
    image: nginx:${NGINX_VERSION}
    container_name: nginx-of-bind-mount-container
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /root
    volumes:
      - type: bind
        source: ${SOURCE_DATA_DIR}
        target: ${TARGET_DATA_DIR}
        bind:
          create_host_path: true
      - type: bind
        source: ${SOURCE_WORK_DIR}
        target: ${TARGET_WORK_DIR}
        bind:
          create_host_path: true