services:
  java-of-bind-mount:
    image: eclipse-temurin:$JAVA_VERSION
    container_name: java-of-bind-mount-container
    network_mode: "host"
    stdin_open: true
    tty: true
    working_dir: /bind-mount
    volumes:
      - type: bind
        source: $SOURCE
        target: /bind-mount
        bind:
          create_host_path: true
