services:
  amazonlinux-2-with-user-of-bind-mount:
    image: amazonlinux-2-with-user:$AMAZONLINUX_2_WITH_USER_VERSION
    build:
      context: .
      args:
        AMAZONLINUX_VERSION: 2
        UNAME: $UNAME
        PW: $PW
    container_name: amazonlinux-2-with-user-of-bind-mount-container
    network_mode: "host"
    stdin_open: true
    tty: true
    user: $UNAME
    working_dir: /home/$UNAME
    volumes:
      - type: bind
        source: $SOURCE
        target: /home/$UNAME/bind-mount
        bind:
          create_host_path: true
