services:
  amazonlinux-2-with-user-of-bind-mount:
    image: amazonlinux-2-with-user:${AMAZONLINUX_2_WITH_USER_VERSION}
    build:
      context: ./
      args:
        USER_NAME: ${USER_NAME}
        USER_PW: ${USER_PW}
    container_name: amazonlinux-2-with-user-of-bind-mount-container
    network_mode: host
    stdin_open: true
    tty: true
    user: ${USER_NAME}
    working_dir: /home/${USER_NAME}
    volumes:
      - type: bind
        source: ${SOURCE_DIR}
        target: ${TARGET_DIR}
        bind:
          create_host_path: true