services:
  postgresql-of-bind-mount:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresql-of-bind-mount-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    stdin_open: true
    tty: true
    working_dir: /root
    volumes:
      - type: bind
        source: ${SOURCE_INIT_DIR}
        target: ${TARGET_INIT_DIR}
        bind:
          create_host_path: true
      - type: bind
        source: ${SOURCE_DATA_DIR}
        target: ${TARGET_DATA_DIR}
        bind:
          create_host_path: true
      - type: bind
        source: ${SOURCE_WORK_DIR}
        target: ${TARGET_WORK_DIR}
        bind:
          create_host_path: true