services:
  postgresql-of-bind-mount:
    image: postgres:$POSTGRES_VERSION
    container_name: postgresql-of-bind-mount-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    stdin_open: true
    tty: true
    working_dir: /bind-mount-work
    volumes:
      - type: bind
        source: $SOURCE_INIT
        target: /docker-entrypoint-initdb.d
        bind:
          create_host_path: true
      - type: bind
        source: $SOURCE_DATA
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
      - type: bind
        source: $SOURCE_WORK
        target: /bind-mount-work
        bind:
          create_host_path: true
