services:
  ubuntu-with-user:
    image: ubuntu-with-user:${UBUNTU_VERSION}
    build:
      context: ./
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
        PW: ${PW}
    container_name: ubuntu-with-user-container
    network_mode: host
    stdin_open: true
    tty: true
    user: ${USER_NAME}:${GROUP_NAME}
    working_dir: /home/${USER_NAME}